<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\osu.Game.Plugins\osu.Game.Plugins.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ppy.osu.Game" Version="2026.505.0">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="ppy.osu.Game.Rulesets.Osu" Version="2026.505.0">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Fody" Version="6.9.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <ProjectReference Include="..\AccessItEasy\AccessItEasy\AccessItEasy.csproj">
      <!-- AccessItEasy only contains marker types, references were removed when weaving -->
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\AccessItEasy\AccessItEasy.Fody\AccessItEasy.Fody.csproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
      <OutputItemType>WeaverFiles</OutputItemType>
    </ProjectReference>
  </ItemGroup>

</Project>
